[phases.setup]
aptPkgs = [
    "python3.11",
    "python3.11-dev",
    "python3-pip",
    "python3-venv",
    "ffmpeg",
    "build-essential",
    "libffi-dev",
    "libnacl-dev",
    "ca-certificates",
    "openssl"
]

[phases.install]
cmds = [
    "python3.11 -m venv /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install --upgrade pip",
    "pip install wheel",
    "pip install certifi",
    "pip install --upgrade certifi",
    "python3.11 -m pip install --upgrade pip setuptools wheel",
    "update-ca-certificates --fresh",
    "export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt",
    "export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt",
    "pip install -r requirements.txt",
    "pip install -e .",
    "yt-dlp --update"
]

[start]
cmd = ". /opt/venv/bin/activate && export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt && export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt && PYTHONPATH=/app python src/bot.py" 