[phases.setup]
aptPkgs = [
    "python3.11",
    "python3.11-dev",
    "python3-pip",
    "ffmpeg",
    "build-essential",
    "libffi-dev",
    "libnacl-dev"
]

[phases.install]
cmds = [
    "python3.11 -m pip install --upgrade pip",
    "python3.11 -m pip install wheel",
    "python3.11 -m pip install -r requirements.txt"
]

[start]
cmd = "python3.11 src/bot.py" 