[phases.setup]
nixPkgs = [
    "python311",
    "python311Packages.pip",
    "python311Packages.setuptools",
    "python311Packages.wheel",
    "ffmpeg",
    "gcc"
]

[phases.install]
cmds = [
    "python3.11 -m venv /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install --upgrade pip",
    "pip install wheel",
    "pip install -r requirements.txt",
    "pip install -e ."
]

[start]
cmd = ". /opt/venv/bin/activate && PYTHONPATH=/app python src/bot.py" 