[phases.setup]
nixPkgs = ["python311", "ffmpeg", "python311Packages.pip", "gcc", "python311Packages.wheel"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "python src/bot.py" 