[phases.setup]
aptPkgs = [
    "python3.11",
    "python3.11-dev",
    "python3-pip",
    "python3-venv",
    "ffmpeg",
    "build-essential",
    "libffi-dev",
    "libnacl-dev",
    "ca-certificates"
]

[phases.install]
cmds = [
    "python3.11 -m venv /opt/venv",
    ". /opt/venv/bin/activate",
    "pip install --upgrade pip",
    "pip install wheel",
    "pip install certifi",
    "pip install -r requirements.txt",
    "pip install -e ."
]

[start]
cmd = ". /opt/venv/bin/activate && PYTHONPATH=/app SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt python src/bot.py" 