[build]
builder = "nixpacks"
buildCommand = "python3.11 -m venv /opt/venv && . /opt/venv/bin/activate && pip install --upgrade pip && pip install wheel && pip install -r requirements.txt && pip install -e ."

[deploy]
startCommand = ". /opt/venv/bin/activate && PYTHONPATH=/app SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt python src/bot.py"
restartPolicyType = "on_failure"
healthcheckPath = "/"
healthcheckTimeout = 100

[build.env]
PYTHON_VERSION = "3.11.7"
NIXPACKS_PYTHON_VERSION = "3.11.7"
PATH = "/opt/venv/bin:$PATH"
PYTHONPATH = "/app"
SSL_CERT_FILE = "/etc/ssl/certs/ca-certificates.crt" 