[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "python src/bot.py"
restartPolicyType = "on_failure"

[[build.buildpacks]]
uri = "heroku/python"

[[build.buildpacks]]
uri = "https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest.git"

[build.env]
PYTHON_VERSION = "3.11.7" 