[build]
builder = "nixpacks"
buildCommand = ". /opt/venv/bin/activate && pip install -r requirements.txt"

[deploy]
startCommand = ". /opt/venv/bin/activate && python src/bot.py"
restartPolicyType = "on_failure"
healthcheckPath = "/"
healthcheckTimeout = 100

[build.env]
PYTHON_VERSION = "3.11.7"
NIXPACKS_PYTHON_VERSION = "3.11.7"
PATH = "/opt/venv/bin:$PATH" 